#!/bin/sh -ef

get_size() {
    _s=${1:-0}
    if [ "$_s" -ge 1048576 ]; then
        hum=$((_s / 1048576)).$(((_s % 1048576) * 10 / 1048576))GB
    elif [ "$_s" -ge 1024 ]; then
        hum=$((_s / 1024)).$(((_s % 1024) * 10 / 1024))MB
    else
        hum=${_s}KB
    fi
    printf '%s\t%s\n' "$hum" "$2"
}

[ "$1" ] || set -- "${PWD##*/}"

kiss list "${1:-null}" >/dev/null || {
    printf 'usage: kiss-size [pkg]\n'
    exit 1
}

sed -e "s|^|$KISS_ROOT|" -e 's|.*/$||' \
    "$KISS_ROOT/var/db/kiss/installed/$1/manifest" \
    | xargs du -sk -- 2>/dev/null |
while read -r size file || {
    get_size "${tot:-0}" total >&2
    break
} do
    get_size "$size" "$file"
    tot=$((${tot:-0} + size))
done
