#!/bin/sh -e

# Display packages which depend on package

[ "$1" ] || set -- "${PWD##*/}"

IFS=:
for repo in $KISS_PATH; do
    [ -d "$repo" ] || continue
    (cd "$repo" && grep -E "^$1( |$)" -- */depends 2>/dev/null) || true
done
